import { BenefitTestConfig } from './eligibility.types';

export const BENEFIT_TEST_CONFIGS: Record<string, BenefitTestConfig> = {
  TR_BIRTH_GRANT: {
    benefitCode: 'TR_BIRTH_GRANT',
    route: '/dogum-yardimi',
    title: 'Doğum Yardımı Testi',
    subtitle: 'Canlı doğum, kayıt ve başvuru uygunluğu için ön değerlendirme.',
    submitLabel: 'Doğum Yardımını Değerlendir',
    roadmapKey: 'TR_BIRTH_GRANT',
    fields: [
      {
        key: 'child_is_live_birth',
        label: 'Çocuk canlı doğdu mu?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
      {
        key: 'previous_live_children_count',
        label: 'Önceki canlı çocuk sayısı',
        type: 'number',
        min: 0,
        max: 20,
        placeholder: 'Örn. 1',
      },
      {
        key: 'applicant_is_turkish_citizen',
        label: 'Başvuru sahibi T.C. vatandaşı mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
      {
        key: 'child_is_kps_registered',
        label: 'Çocuğun KPS kaydı var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
      {
        key: 'child_resides_in_tr',
        label: 'Çocuk Türkiye’de mi yaşıyor?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
      {
        key: 'child_birth_date',
        label: 'Doğum tarihi',
        type: 'date',
        placeholder: 'YYYY-AA-GG',
      },
    ],
  },
  TR_DISABILITY_PENSION: {
    benefitCode: 'TR_DISABILITY_PENSION',
    route: '/engelli-maasi',
    title: 'Engelli Maaşı Testi',
    subtitle: 'Gelir, engellilik oranı ve sağlık raporu üzerinden ön değerlendirme.',
    submitLabel: 'Engelli Maaşını Değerlendir',
    roadmapKey: 'TR_DISABILITY_PENSION',
    fields: [
      {
        key: 'age',
        label: 'Yaş',
        type: 'number',
        min: 0,
        max: 120,
        placeholder: 'Örn. 41',
      },
      {
        key: 'household_total_income',
        label: 'Hane toplam aylık geliri (TL)',
        type: 'number',
        min: 0,
        max: 100000000,
        step: 0.01,
        placeholder: 'Örn. 18000',
      },
      {
        key: 'household_size',
        label: 'Hanede yaşayan kişi sayısı',
        type: 'number',
        min: 1,
        max: 20,
        placeholder: 'Örn. 4',
      },
      {
        key: 'has_social_security',
        label: 'Sosyal güvence var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'has_valid_medical_report',
        label: 'Geçerli sağlık kurulu raporu var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'disability_rate',
        label: 'Engellilik oranı (%)',
        type: 'number',
        min: 0,
        max: 100,
        placeholder: 'Örn. 40',
      },
    ],
  },
  TR_GSS: {
    benefitCode: 'TR_GSS',
    route: '/gss',
    title: 'GSS Gelir Testi',
    subtitle: 'Genel Sağlık Sigortası kapsamı için gelir ve güvence değerlendirmesi.',
    submitLabel: 'GSS’yi Değerlendir',
    roadmapKey: 'TR_GSS',
    fields: [
      {
        key: 'gross_household_income',
        label: 'Brüt hane aylık geliri (TL)',
        type: 'number',
        min: 0,
        max: 100000000,
        step: 0.01,
        placeholder: 'Örn. 14000',
      },
      {
        key: 'household_size',
        label: 'Hanede yaşayan kişi sayısı',
        type: 'number',
        min: 1,
        max: 20,
        placeholder: 'Örn. 3',
      },
      {
        key: 'has_social_security',
        label: 'Sosyal güvence var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'has_active_insurance',
        label: 'Aktif sigorta kaydı var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'is_covered_as_dependent',
        label: 'Bakmakla yükümlü olunan kişi kapsamında mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
    ],
  },
  TR_OLD_AGE_PENSION: {
    benefitCode: 'TR_OLD_AGE_PENSION',
    route: '/65-yas-ayligi',
    title: '65 Yaş Aylığı Testi',
    subtitle: 'Yaş, gelir ve sosyal güvence üzerinden ön değerlendirme.',
    submitLabel: '65 Yaş Aylığını Değerlendir',
    roadmapKey: 'TR_OLD_AGE_PENSION',
    fields: [
      {
        key: 'age',
        label: 'Yaş',
        type: 'number',
        min: 0,
        max: 120,
        placeholder: 'Örn. 67',
      },
      {
        key: 'has_spouse',
        label: 'Eşi var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'self_monthly_income',
        label: 'Kişisel aylık gelir (TL)',
        type: 'number',
        min: 0,
        max: 100000000,
        step: 0.01,
        placeholder: 'Örn. 7500',
      },
      {
        key: 'spouse_monthly_income',
        label: 'Eş aylık geliri (TL)',
        type: 'number',
        min: 0,
        max: 100000000,
        step: 0.01,
        placeholder: 'Örn. 5000',
      },
      {
        key: 'has_social_security',
        label: 'Sosyal güvence var mı?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Var', value: true },
          { label: 'Yok', value: false },
        ],
      },
      {
        key: 'receives_pension',
        label: 'Emekli aylığı alıyor musunuz?',
        type: 'select',
        options: [
          { label: 'Belirtilmedi', value: '' },
          { label: 'Evet', value: true },
          { label: 'Hayır', value: false },
        ],
      },
    ],
  },
};

export const TEST_CATALOG = [
  {
    title: 'Evde Bakım',
    description: 'Hane, sağlık ve bakım uygunluğu için çok adımlı değerlendirme.',
    route: '/evde-bakim',
    benefitCode: 'TR_HOME_CARE_ALLOWANCE',
  },
  {
    title: 'Doğum Yardımı',
    description: 'Canlı doğum ve kayıt koşullarına dayalı ön değerlendirme.',
    route: '/dogum-yardimi',
    benefitCode: 'TR_BIRTH_GRANT',
  },
  {
    title: 'Engelli Maaşı',
    description: 'Engellilik oranı, sağlık raporu ve gelir testi ile değerlendirme.',
    route: '/engelli-maasi',
    benefitCode: 'TR_DISABILITY_PENSION',
  },
  {
    title: 'GSS Gelir Testi',
    description: 'Genel sağlık sigortası kapsamı için gelir ve güvence kontrolü.',
    route: '/gss',
    benefitCode: 'TR_GSS',
  },
  {
    title: '65 Yaş Aylığı',
    description: 'Yaş, gelir ve sosyal güvence üzerinden yol gösterici kontrol.',
    route: '/65-yas-ayligi',
    benefitCode: 'TR_OLD_AGE_PENSION',
  },
] as const;
